name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to use for the release."
        required: true
        default: "X.Y"
      releaseBody:
        description: "Information about the release"
        required: true
        default: "New release"
jobs:
  Release:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
        with:
          ref: main
      - name: Set up python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: '3.11'
      - name: Build
        run: make compile-with-docker-all
      - name: Run Integ Tests
        run: |
          make tests-with-docker
          make integ-tests
      - name: Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65  # v2.6.2
        with:
          name: Release ${{ github.event.inputs.releaseVersion }}
          tag_name: v${{ github.event.inputs.releaseVersion }}
          body: ${{ github.event.inputs.releaseBody }}
          files: |
            bin/aws-lambda-rie
            bin/aws-lambda-rie-arm64
            bin/aws-lambda-rie-x86_64
